spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/radar_macro
spring.datasource.username=radar
spring.datasource.password=radar123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.config.import=optional:classpath:env.properties